// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBpKnnflsCAiXX_mVLECmAN_L-K3Cz9HU',
    appId: '1:93988431301:web:95f86111272480c98b57ac',
    messagingSenderId: '93988431301',
    projectId: 'chat-app-dc9c3',
    authDomain: 'chat-app-dc9c3.firebaseapp.com',
    storageBucket: 'chat-app-dc9c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfjxTjDZxWW8XIPOU3j83s7Wj5RrshfiA',
    appId: '1:93988431301:android:6824d3b145f392098b57ac',
    messagingSenderId: '93988431301',
    projectId: 'chat-app-dc9c3',
    storageBucket: 'chat-app-dc9c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmc6U2NSkqevzmY9bMxjOxGTLzZ6xhFF4',
    appId: '1:93988431301:ios:a7cca7237569262f8b57ac',
    messagingSenderId: '93988431301',
    projectId: 'chat-app-dc9c3',
    storageBucket: 'chat-app-dc9c3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmc6U2NSkqevzmY9bMxjOxGTLzZ6xhFF4',
    appId: '1:93988431301:ios:6c94fd7f0509ab908b57ac',
    messagingSenderId: '93988431301',
    projectId: 'chat-app-dc9c3',
    storageBucket: 'chat-app-dc9c3.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
